"""empty message

Revision ID: 218bd5290b68
Revises: ec9112a07f44
Create Date: 2020-12-05 13:29:35.353819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '218bd5290b68'
down_revision = 'ec9112a07f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABSENT', 'PRESENT', 'HALF_DAY', name='status'), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
