"""added student section

Revision ID: 474b836cd015
Revises: 3975441c5756
Create Date: 2020-12-14 13:17:57.443449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474b836cd015'
down_revision = '3975441c5756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('section', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'section')
    # ### end Alembic commands ###
