"""added fee table

Revision ID: 6d571824b193
Revises: 
Create Date: 2020-12-20 15:31:26.940273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d571824b193'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file', sa.String(length=512), nullable=True),
    sa.Column('text', sa.String(length=5000), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enquiry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.String(length=512), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('father_name', sa.String(length=512), nullable=False),
    sa.Column('interested_class', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_structure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=6), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('session', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gendertype'), nullable=False),
    sa.Column('student_class', sa.String(length=32), nullable=False),
    sa.Column('section', sa.String(length=6), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('father_name', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('tc', sa.String(length=512), nullable=True),
    sa.Column('photo', sa.String(length=512), nullable=True),
    sa.Column('migration', sa.String(length=512), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gendertype'), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('father_name', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('photo', sa.String(length=512), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABSENT', 'HALF_DAY', 'PRESENT', name='status'), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_student_id'), 'attendance', ['student_id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=6), nullable=True),
    sa.Column('section', sa.String(length=3), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_teacher_id'), 'classes', ['teacher_id'], unique=False)
    op.create_table('fee_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('session', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=64), nullable=False),
    sa.Column('months', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_transactions_student_id'), 'fee_transactions', ['student_id'], unique=False)
    op.create_table('solution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solution_file', sa.String(length=512), nullable=True),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_assignment_id'), 'solution', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_solution_student_id'), 'solution', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solution_student_id'), table_name='solution')
    op.drop_index(op.f('ix_solution_assignment_id'), table_name='solution')
    op.drop_table('solution')
    op.drop_index(op.f('ix_fee_transactions_student_id'), table_name='fee_transactions')
    op.drop_table('fee_transactions')
    op.drop_index(op.f('ix_classes_teacher_id'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_attendance_student_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('fee_structure')
    op.drop_table('enquiry')
    op.drop_table('assignments')
    # ### end Alembic commands ###
