"""empty message

Revision ID: 70df10de2543
Revises: 5f6faca2ebfe
Create Date: 2020-12-22 13:53:03.661329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70df10de2543'
down_revision = '5f6faca2ebfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('session', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'session')
    # ### end Alembic commands ###
