"""enquiry table added

Revision ID: 909bee35797a
Revises: 474b836cd015
Create Date: 2020-12-14 15:00:59.064510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909bee35797a'
down_revision = '474b836cd015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.String(length=512), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('father_name', sa.String(length=512), nullable=False),
    sa.Column('interested_class', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enquiry')
    # ### end Alembic commands ###
