"""empty message

Revision ID: 944c3b514095
Revises: e95dd286d3e8
Create Date: 2020-12-08 17:54:16.704933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '944c3b514095'
down_revision = 'e95dd286d3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solution_file', sa.String(length=512), nullable=True),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_assignment_id'), 'solution', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_solution_student_id'), 'solution', ['student_id'], unique=False)
    op.drop_index('ix_solutions_assignment_id', table_name='solutions')
    op.drop_index('ix_solutions_student_id', table_name='solutions')
    op.drop_table('solutions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('solution_file', sa.VARCHAR(length=512), nullable=True),
    sa.Column('comment', sa.VARCHAR(length=512), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_solutions_student_id', 'solutions', ['student_id'], unique=False)
    op.create_index('ix_solutions_assignment_id', 'solutions', ['assignment_id'], unique=False)
    op.drop_index(op.f('ix_solution_student_id'), table_name='solution')
    op.drop_index(op.f('ix_solution_assignment_id'), table_name='solution')
    op.drop_table('solution')
    # ### end Alembic commands ###
