"""empty message

Revision ID: e95dd286d3e8
Revises: 14918abd3790
Create Date: 2020-12-08 17:29:23.149651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95dd286d3e8'
down_revision = '14918abd3790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solution_file', sa.String(length=512), nullable=True),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_assignment_id'), 'solution', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_solutions_student_id'), 'solution', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solutions_student_id'), table_name='solution')
    op.drop_index(op.f('ix_solutions_assignment_id'), table_name='solution')
    op.drop_table('solution')
    # ### end Alembic commands ###
