"""empty message

Revision ID: ec9112a07f44
Revises: 
Create Date: 2020-12-05 13:22:55.112752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9112a07f44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gendertype'), nullable=False),
    sa.Column('student_class', sa.String(length=32), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('father_name', sa.String(length=256), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('tc', sa.String(length=512), nullable=True),
    sa.Column('migration', sa.String(length=512), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###
